language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt


deploy:
  provider: pypi
  username: __token__
  password: ${MASKTOKEN}
  skip_cleanup: true
  on:
    python: 3.6
    branch: master
